### ISSUE TITLE
RS01 Definir lógica interna de las piezas

### ISSUE THREAD

**Issue by storress** [m4droid/logisim#18]
Requisito de Software 
Funcionalidad que permite que los componentes previamente diseñados, tengan el comportamiento esperado.
- [x] #19 - Logica interna del pulsor 
- [x] #21 - Logica interna del reloj 
- [x] #23 - Logica interna de la protoboard
- [x] #24 - Logica interna de LEDs
- [x] #30 - Logica interna de la compuerta AND
- [x] #34 - Logica interna de la compuerta OR
- [x] #35 - Logica interna de la compuerta NOT
- [x] #36 - Logica interna de la compuerta NAND
- [x] #39 - Logica interna Generador de Voltaje
- [x] #44 - Logica interna de la compuerta FLIP FLOP

**Comment by m4droid** [comment]
De acuerdo al equipo de trabajo, la lógica se implementó correctamente.
