### ISSUE TITLE
RS Implementar logica interna componente Protoboard

### ISSUE THREAD

**Issue by moishernadez** [m4droid/logisim#23]
- [x] Iteracion 1
  - [x] Crear Canal central #13  
  - [x] Crear buses #13
  - [x] Crear pistas de alimentación #13 
  - [x] Conectar internamente los pines de las pistas, buses y canales centrales  #13

**Comment by zero1712** [comment]
De acuerdo a las últimas decisiones del equipo, se trabajara en la solución brindada por mariocesarc (branch: tunnelproto )

Nuestra segunda opción, solución brindada por mi, no se utilizara por el momento.
(branch: protoboard-button)
